/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypologyRouteImport } from './routes/typology'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoneToolsRouteImport } from './routes/stone-tools'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MuseumsRouteImport } from './routes/museums'
import { Route as HeritageLawsRouteImport } from './routes/heritage-laws'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TypologyRoute = TypologyRouteImport.update({
  id: '/typology',
  path: '/typology',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneToolsRoute = StoneToolsRouteImport.update({
  id: '/stone-tools',
  path: '/stone-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsRoute = MuseumsRouteImport.update({
  id: '/museums',
  path: '/museums',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageLawsRoute = HeritageLawsRouteImport.update({
  id: '/heritage-laws',
  path: '/heritage-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attributions': typeof AttributionsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/field-notes': typeof FieldNotesRoute
  '/heritage-laws': typeof HeritageLawsRoute
  '/museums': typeof MuseumsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/references': typeof ReferencesRoute
  '/sites': typeof SitesRoute
  '/stone-tools': typeof StoneToolsRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/typology': typeof TypologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attributions': typeof AttributionsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/field-notes': typeof FieldNotesRoute
  '/heritage-laws': typeof HeritageLawsRoute
  '/museums': typeof MuseumsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/references': typeof ReferencesRoute
  '/sites': typeof SitesRoute
  '/stone-tools': typeof StoneToolsRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/typology': typeof TypologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attributions': typeof AttributionsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/field-notes': typeof FieldNotesRoute
  '/heritage-laws': typeof HeritageLawsRoute
  '/museums': typeof MuseumsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/references': typeof ReferencesRoute
  '/sites': typeof SitesRoute
  '/stone-tools': typeof StoneToolsRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/typology': typeof TypologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attributions'
    | '/auth'
    | '/community'
    | '/contact'
    | '/feedback'
    | '/field-notes'
    | '/heritage-laws'
    | '/museums'
    | '/privacy-policy'
    | '/references'
    | '/sites'
    | '/stone-tools'
    | '/terms'
    | '/timeline'
    | '/typology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attributions'
    | '/auth'
    | '/community'
    | '/contact'
    | '/feedback'
    | '/field-notes'
    | '/heritage-laws'
    | '/museums'
    | '/privacy-policy'
    | '/references'
    | '/sites'
    | '/stone-tools'
    | '/terms'
    | '/timeline'
    | '/typology'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attributions'
    | '/auth'
    | '/community'
    | '/contact'
    | '/feedback'
    | '/field-notes'
    | '/heritage-laws'
    | '/museums'
    | '/privacy-policy'
    | '/references'
    | '/sites'
    | '/stone-tools'
    | '/terms'
    | '/timeline'
    | '/typology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttributionsRoute: typeof AttributionsRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FeedbackRoute: typeof FeedbackRoute
  FieldNotesRoute: typeof FieldNotesRoute
  HeritageLawsRoute: typeof HeritageLawsRoute
  MuseumsRoute: typeof MuseumsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReferencesRoute: typeof ReferencesRoute
  SitesRoute: typeof SitesRoute
  StoneToolsRoute: typeof StoneToolsRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  TypologyRoute: typeof TypologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typology': {
      id: '/typology'
      path: '/typology'
      fullPath: '/typology'
      preLoaderRoute: typeof TypologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone-tools': {
      id: '/stone-tools'
      path: '/stone-tools'
      fullPath: '/stone-tools'
      preLoaderRoute: typeof StoneToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums': {
      id: '/museums'
      path: '/museums'
      fullPath: '/museums'
      preLoaderRoute: typeof MuseumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-laws': {
      id: '/heritage-laws'
      path: '/heritage-laws'
      fullPath: '/heritage-laws'
      preLoaderRoute: typeof HeritageLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttributionsRoute: AttributionsRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FeedbackRoute: FeedbackRoute,
  FieldNotesRoute: FieldNotesRoute,
  HeritageLawsRoute: HeritageLawsRoute,
  MuseumsRoute: MuseumsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReferencesRoute: ReferencesRoute,
  SitesRoute: SitesRoute,
  StoneToolsRoute: StoneToolsRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  TypologyRoute: TypologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
